[tool.poetry]
name = "domain"
version = "0.1.0"
description = "Domain layer of cosmic-ddd"
authors = ["mbalzert@gmail.com"]
packages = [{ include = "domain" }]

[tool.poetry.dependencies]
python = "^3.11"
